# NCR Ride Booking Analytics & Predictive Intelligence Platform

## Notebook 01: Business Understanding and Data Validation

### Objectives

* Understand the ride-booking business problem.
* Load the NCR ride-booking dataset.
* Validate the dataset's rows and columns.
* Inspect data types and missing values.
* Check duplicate records and booking IDs.
* Understand booking status categories.
* Identify potential data-quality issues before cleaning.

In [1]:
# Import the required libraries

import pandas as pd
import numpy as np
from pathlib import Path

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
import pandas as pd

df = pd.read_excel("ncr_ride_bookings.xlsx")

df.head()

,Date,Month Name,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,March,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,0.0,0.0,0,NaN,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
1,2024-11-29,November,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,0,NaN,0,NaN,1,Vehicle Breakdown,237,5.73,0.0,0.0,UPI
2,2024-08-23,August,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,0,NaN,0,NaN,0,NaN,627,13.58,4.9,4.9,Debit Card
3,2024-10-21,October,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,0,NaN,0,NaN,0,NaN,416,34.02,4.6,5.0,UPI
4,2024-09-16,September,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,0,NaN,0,NaN,0,NaN,737,48.21,4.1,4.3,UPI

In [3]:
df.tail()

,Date,Month Name,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
149995,2024-11-11,November,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,0,NaN,0,NaN,0,NaN,475,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,November,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,0,NaN,0,NaN,0,NaN,1093,21.31,4.8,5.0,UPI
149997,2024-09-18,September,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,0,NaN,0,NaN,0,NaN,852,15.93,3.9,4.4,Cash
149998,2024-10-05,October,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,0,NaN,0,NaN,0,NaN,333,45.54,4.1,3.7,UPI
149999,2024-03-10,March,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,0,NaN,0,NaN,0,NaN,806,21.19,4.6,4.9,Credit Card

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[us]
 1   Month Name                         150000 non-null  str
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  str
 4   Booking Status                     150000 non-null  str
 5   Customer ID                        150000 non-null  str
 6   Vehicle Type                       150000 non-null  str
 7   Pickup Location                    150000 non-null  str
 8   Drop Location                      150000 non-null  str
 9   Avg VTAT                           150000 non-null  float64
 10  Avg CTAT                           150000 non-null  float64
 11  Cancelled Rides by Customer        150000 non-null  int64
 12  Reason for cancelling by Customer  10500 non-null   str
 13  Cancelled Rides by Driver          150000 non-null  int64
 14  Driver Cancellation Reason         27000 non-null   str
 15  Incomplete Rides                   150000 non-null  int64
 16  Incomplete Rides Reason            9000 non-null    str
 17  Booking Value                      150000 non-null  int64
 18  Ride Distance                      150000 non-null  float64
 19  Driver Ratings                     150000 non-null  float64
 20  Customer Rating                    150000 non-null  float64
 21  Payment Method                     102000 non-null  str
dtypes: datetime64[us](1), float64(5), int64(4), object(1), str(11)
memory usage: 37.2+ MB

## 2. Missing Value Analysis

**Business objective:** Identify missing data and determine whether it represents a data-quality problem or a legitimate business situation.

We will calculate the number and percentage of missing values in every column before deciding how to handle them.

In [5]:
# Missing value analysis

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_report = missing_report.sort_values(
    by="Missing_Percentage",
    ascending=False
)

display(missing_report)

                                   Missing_Count  Missing_Percentage
Incomplete Rides Reason                   141000                94.0
Reason for cancelling by Customer         139500                93.0
Driver Cancellation Reason                123000                82.0
Payment Method                             48000                32.0
Date                                           0                 0.0
Month Name                                     0                 0.0
Customer ID                                    0                 0.0
Booking Status                                 0                 0.0
Booking ID                                     0                 0.0
Time                                           0                 0.0
Avg VTAT                                       0                 0.0
Vehicle Type                                   0                 0.0
Drop Location                                  0                 0.0
Pickup Location                                0                 0.0
Cancelled Rides by Driver                      0                 0.0
Cancelled Rides by Customer                    0                 0.0
Avg CTAT                                       0                 0.0
Incomplete Rides                               0                 0.0
Booking Value                                  0                 0.0
Ride Distance                                  0                 0.0
Driver Ratings                                 0                 0.0
Customer Rating                                0                 0.0

## 3. Duplicate Record Analysis

**Business objective:** Identify exact duplicate rows and repeated booking IDs.

Repeated booking IDs require investigation, but they are not automatically errors. We must verify the data before removing anything.

In [6]:
# Check exact duplicate rows

duplicate_rows = df.duplicated().sum()

# Check duplicate Booking IDs

duplicate_booking_ids = df["Booking ID"].duplicated().sum()

print("Exact duplicate rows:", duplicate_rows)
print("Repeated Booking IDs:", duplicate_booking_ids)
print("Total rows:", len(df))
print("Unique Booking IDs:", df["Booking ID"].nunique())

Exact duplicate rows: 0
Repeated Booking IDs: 1233
Total rows: 150000
Unique Booking IDs: 148767

## . Duplicate Booking ID Investigation

### Business objective

Investigate why some Booking IDs appear more than once.

### Questions

* Are the repeated records identical in their business information?
* Do repeated Booking IDs have different booking statuses?
* Are the repeated IDs associated with different customers?
* Should these records be retained or investigated further?

We will inspect the records before making any changes.

In [7]:
# Identify all rows with repeated Booking IDs

duplicate_booking_mask = df["Booking ID"].duplicated(keep=False)

duplicate_booking_df = df.loc[
    duplicate_booking_mask
].sort_values("Booking ID")

print("Rows belonging to repeated Booking IDs:",
      len(duplicate_booking_df))

display(duplicate_booking_df.head(20))

Rows belonging to repeated Booking IDs: 2457

,Date,Month Name,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
9192,2024-07-21,July,17:59:41,"""CNR1026036""",No Driver Found,"""CID6974869""",Go Mini,Seelampur,Nehru Place,0.0,0.0,0,NaN,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
81334,2024-10-15,October,18:17:23,"""CNR1026036""",Completed,"""CID6480133""",Go Mini,Khandsa,Ashok Vihar,3.8,43.3,0,NaN,0,NaN,0,NaN,102,36.51,4.9,4.2,UPI
1353,2024-01-19,January,17:00:57,"""CNR1029172""",Incomplete,"""CID2615731""",Bike,Jhilmil,Narsinghpur,4.7,26.7,0,NaN,0,NaN,1,Customer Demand,429,16.16,0.0,0.0,UPI
9587,2024-12-17,December,19:19:02,"""CNR1029172""",Completed,"""CID6382731""",Auto,Inderlok,Laxmi Nagar,6.9,34.4,0,NaN,0,NaN,0,NaN,332,36.38,4.3,4.3,UPI
82029,2024-11-05,November,16:50:20,"""CNR1051228""",Completed,"""CID3177617""",Auto,Dwarka Sector 21,Nehru Place,8.5,24.8,0,NaN,0,NaN,0,NaN,246,4.80,4.6,4.5,UPI
110412,2024-01-31,January,08:42:04,"""CNR1051228""",Completed,"""CID5242056""",Premier Sedan,Arjangarh,Yamuna Bank,14.2,25.4,0,NaN,0,NaN,0,NaN,930,13.06,3.4,4.2,Cash
87333,2024-04-20,April,23:16:21,"""CNR1056023""",Completed,"""CID9367665""",Premier Sedan,Badshahpur,Sultanpur,7.1,25.7,0,NaN,0,NaN,0,NaN,116,46.54,3.8,5.0,Credit Card
120008,2024-07-07,July,17:18:49,"""CNR1056023""",Incomplete,"""CID4890470""",Go Sedan,Meerut,Tilak Nagar,6.6,24.2,0,NaN,0,NaN,1,Customer Demand,420,5.13,0.0,0.0,Uber Wallet
38548,2024-10-15,October,13:33:55,"""CNR1058956""",Completed,"""CID1882606""",Go Mini,Badshahpur,MG Road,3.7,20.2,0,NaN,0,NaN,0,NaN,194,24.65,4.3,4.3,Cash
71570,2024-02-12,February,19:02:47,"""CNR1058956""",Cancelled by Customer,"""CID2451799""",Premier Sedan,Patel Chowk,Kaushambi,19.9,0.0,1,Wrong Address,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
92822,2024-03-24,March,11:11:19,"""CNR1071255""",Cancelled by Driver,"""CID4222557""",Go Mini,MG Road,Moolchand,3.2,0.0,0,NaN,1,Personal & Car related issues,0,NaN,0,0.00,0.0,0.0,NaN
94087,2024-03-21,March,07:35:07,"""CNR1071255""",Completed,"""CID4439810""",Go Sedan,Ghaziabad,Ramesh Nagar,7.0,34.3,0,NaN,0,NaN,0,NaN,436,15.37,4.3,4.3,Cash
18828,2024-10-07,October,20:06:47,"""CNR1076471""",Completed,"""CID8425781""",Go Sedan,Ashok Vihar,Yamuna Bank,4.0,26.1,0,NaN,0,NaN,0,NaN,116,24.14,4.2,4.6,UPI
23113,2024-02-12,February,12:58:19,"""CNR1076471""",Completed,"""CID3616321""",Bike,Rohini West,Anand Vihar ISBT,14.3,41.4,0,NaN,0,NaN,0,NaN,976,47.37,4.3,4.3,Uber Wallet
82485,2024-08-20,August,11:29:28,"""CNR1077779""",Completed,"""CID2252556""",Go Mini,Vasant Kunj,Indraprastha,8.8,26.1,0,NaN,0,NaN,0,NaN,889,40.35,4.3,4.7,Cash
87568,2024-11-05,November,17:32:53,"""CNR1077779""",Cancelled by Customer,"""CID6213303""",Premier Sedan,Greater Kailash,Madipur,19.0,0.0,1,Driver is not moving towards pickup location,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
26279,2024-11-27,November,20:54:07,"""CNR1079962""",Completed,"""CID1039185""",Go Sedan,Mansarovar Park,Model Town,2.9,42.5,0,NaN,0,NaN,0,NaN,331,19.73,4.3,4.2,Cash
148881,2024-12-15,December,09:21:59,"""CNR1079962""",Completed,"""CID1210517""",Auto,Nirman Vihar,Maidan Garhi,14.6,27.7,0,NaN,0,NaN,0,NaN,117,13.96,3.1,4.9,UPI
100164,2024-07-04,July,15:46:39,"""CNR1091682""",Cancelled by Customer,"""CID1131593""",Go Mini,Vishwavidyalaya,Botanical Garden,13.7,0.0,1,Change of plans,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
111121,2024-08-13,August,10:39:17,"""CNR1091682""",Completed,"""CID1590844""",eBike,Punjabi Bagh,Khan Market,7.4,43.0,0,NaN,0,NaN,0,NaN,786,5.59,4.6,4.3,Credit Card

In [8]:
# Count the number of rows for each repeated Booking ID

repeated_id_counts = (
    duplicate_booking_df
    .groupby("Booking ID")
    .size()
    .sort_values(ascending=False)
)

print("Number of repeated Booking IDs:",
      repeated_id_counts.size)

print("\nMost frequently repeated Booking IDs:")
display(repeated_id_counts.head(10))

Number of repeated Booking IDs: 1224

Most frequently repeated Booking IDs:

Booking ID
"CNR3648267"    3
"CNR5292943"    3
"CNR2726142"    3
"CNR6337479"    3
"CNR7199036"    3
"CNR7585544"    3
"CNR7642097"    3
"CNR7908610"    3
"CNR9603232"    3
"CNR1026036"    2
dtype: int64

In [9]:
# Count distinct booking statuses for each repeated Booking ID

status_variation = (
    duplicate_booking_df
    .groupby("Booking ID")["Booking Status"]
    .nunique()
)

print(
    "Repeated IDs with multiple booking statuses:",
    (status_variation > 1).sum()
)

print(
    "Repeated IDs with only one booking status:",
    (status_variation == 1).sum()
)

Repeated IDs with multiple booking statuses: 731
Repeated IDs with only one booking status: 493

In [10]:
# Count distinct customers associated with each repeated Booking ID

customer_variation = (
    duplicate_booking_df
    .groupby("Booking ID")["Customer ID"]
    .nunique()
)

print(
    "Repeated IDs linked to multiple customers:",
    (customer_variation > 1).sum()
)

print(
    "Repeated IDs linked to one customer:",
    (customer_variation == 1).sum()
)

Repeated IDs linked to multiple customers: 1224
Repeated IDs linked to one customer: 0

## Booking ID Quality Investigation

### Business objective

Determine whether repeated Booking IDs represent a data-quality problem.

We will inspect the format of Booking IDs, identify repeated records, and compare their booking dates, customers, and statuses.

No records will be deleted until the investigation is complete.

In [11]:
# Inspect the Booking ID format

print("Sample Booking IDs:")
display(df["Booking ID"].head(10))

print("\nBooking ID data type:")
print(df["Booking ID"].dtype)

print("\nNumber of unique Booking IDs:")
print(df["Booking ID"].nunique())

print("\nTotal number of rows:")
print(len(df))

Sample Booking IDs:

0    "CNR5884300"
1    "CNR1326809"
2    "CNR8494506"
3    "CNR8906825"
4    "CNR1950162"
5    "CNR4096693"
6    "CNR2002539"
7    "CNR6568000"
8    "CNR4510807"
9    "CNR7721892"
Name: Booking ID, dtype: str

Booking ID data type:
str

Number of unique Booking IDs:
148767

Total number of rows:
150000

In [12]:
# Inspect all records for one repeated Booking ID

sample_booking_id = "CNR1026036"

sample_records = df[
    df["Booking ID"] == sample_booking_id
]

display(sample_records)

Empty DataFrame
Columns: [Date, Month Name, Time, Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Driver Cancellation Reason, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating, Payment Method]
Index: []

In [13]:
# Check the date range

print("Earliest booking date:", df["Date"].min())
print("Latest booking date:", df["Date"].max())

print("\nNumber of unique booking dates:")
print(df["Date"].nunique())

print("\nMissing dates:")
print(df["Date"].isnull().sum())

Earliest booking date: 2024-01-01 00:00:00
Latest booking date: 2024-12-30 00:00:00

Number of unique booking dates:
365

Missing dates:
0

In [14]:
# Check the number of unique values in important categorical columns

categorical_columns = [
    "Booking Status",
    "Vehicle Type",
    "Payment Method",
    "Pickup Location",
    "Drop Location"
]

for column in categorical_columns:
    print(f"\n{column}")
    print("Unique categories:", df[column].nunique())
    print("Missing values:", df[column].isnull().sum())

Booking Status
Unique categories: 5
Missing values: 0

Vehicle Type
Unique categories: 7
Missing values: 0

Payment Method
Unique categories: 5
Missing values: 48000

Pickup Location
Unique categories: 176
Missing values: 0

Drop Location
Unique categories: 176
Missing values: 0

#  — Booking Status and Data Quality Investigation

## Business Objective

Understand booking outcomes and investigate whether the dataset follows expected business rules.

## Questions to Answer

1. How many bookings belong to each booking status?
2. What percentage of bookings fall into each status?
3. Are repeated Booking IDs associated with different booking statuses?
4. Are cancellation and incomplete-ride indicators consistent with Booking Status?
5. Are there unexpected categories or values in the dataset?

## Business Importance

These checks help us understand booking outcomes and identify potential data-quality problems before cleaning the dataset or developing machine-learning models.

In [16]:
# Analyze booking status distribution

status_counts = df["Booking Status"].value_counts()

status_percentage = (
    df["Booking Status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

status_summary = pd.DataFrame({
    "Booking_Count": status_counts,
    "Percentage": status_percentage
})

display(status_summary)

                       Booking_Count  Percentage
Booking Status
Completed                      93000        62.0
Cancelled by Driver            27000        18.0
No Driver Found                10500         7.0
Cancelled by Customer          10500         7.0
Incomplete                      9000         6.0

In [17]:
# Find all records with repeated Booking IDs

duplicate_booking_mask = df["Booking ID"].duplicated(
    keep=False
)

duplicate_booking_df = (
    df.loc[duplicate_booking_mask]
    .sort_values("Booking ID")
)

print("Total rows with repeated Booking IDs:",
      len(duplicate_booking_df))

print("Unique repeated Booking IDs:",
      duplicate_booking_df["Booking ID"].nunique())

display(duplicate_booking_df.head(20))

Total rows with repeated Booking IDs: 2457
Unique repeated Booking IDs: 1224

,Date,Month Name,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
9192,2024-07-21,July,17:59:41,"""CNR1026036""",No Driver Found,"""CID6974869""",Go Mini,Seelampur,Nehru Place,0.0,0.0,0,NaN,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
81334,2024-10-15,October,18:17:23,"""CNR1026036""",Completed,"""CID6480133""",Go Mini,Khandsa,Ashok Vihar,3.8,43.3,0,NaN,0,NaN,0,NaN,102,36.51,4.9,4.2,UPI
1353,2024-01-19,January,17:00:57,"""CNR1029172""",Incomplete,"""CID2615731""",Bike,Jhilmil,Narsinghpur,4.7,26.7,0,NaN,0,NaN,1,Customer Demand,429,16.16,0.0,0.0,UPI
9587,2024-12-17,December,19:19:02,"""CNR1029172""",Completed,"""CID6382731""",Auto,Inderlok,Laxmi Nagar,6.9,34.4,0,NaN,0,NaN,0,NaN,332,36.38,4.3,4.3,UPI
82029,2024-11-05,November,16:50:20,"""CNR1051228""",Completed,"""CID3177617""",Auto,Dwarka Sector 21,Nehru Place,8.5,24.8,0,NaN,0,NaN,0,NaN,246,4.80,4.6,4.5,UPI
110412,2024-01-31,January,08:42:04,"""CNR1051228""",Completed,"""CID5242056""",Premier Sedan,Arjangarh,Yamuna Bank,14.2,25.4,0,NaN,0,NaN,0,NaN,930,13.06,3.4,4.2,Cash
87333,2024-04-20,April,23:16:21,"""CNR1056023""",Completed,"""CID9367665""",Premier Sedan,Badshahpur,Sultanpur,7.1,25.7,0,NaN,0,NaN,0,NaN,116,46.54,3.8,5.0,Credit Card
120008,2024-07-07,July,17:18:49,"""CNR1056023""",Incomplete,"""CID4890470""",Go Sedan,Meerut,Tilak Nagar,6.6,24.2,0,NaN,0,NaN,1,Customer Demand,420,5.13,0.0,0.0,Uber Wallet
38548,2024-10-15,October,13:33:55,"""CNR1058956""",Completed,"""CID1882606""",Go Mini,Badshahpur,MG Road,3.7,20.2,0,NaN,0,NaN,0,NaN,194,24.65,4.3,4.3,Cash
71570,2024-02-12,February,19:02:47,"""CNR1058956""",Cancelled by Customer,"""CID2451799""",Premier Sedan,Patel Chowk,Kaushambi,19.9,0.0,1,Wrong Address,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
92822,2024-03-24,March,11:11:19,"""CNR1071255""",Cancelled by Driver,"""CID4222557""",Go Mini,MG Road,Moolchand,3.2,0.0,0,NaN,1,Personal & Car related issues,0,NaN,0,0.00,0.0,0.0,NaN
94087,2024-03-21,March,07:35:07,"""CNR1071255""",Completed,"""CID4439810""",Go Sedan,Ghaziabad,Ramesh Nagar,7.0,34.3,0,NaN,0,NaN,0,NaN,436,15.37,4.3,4.3,Cash
18828,2024-10-07,October,20:06:47,"""CNR1076471""",Completed,"""CID8425781""",Go Sedan,Ashok Vihar,Yamuna Bank,4.0,26.1,0,NaN,0,NaN,0,NaN,116,24.14,4.2,4.6,UPI
23113,2024-02-12,February,12:58:19,"""CNR1076471""",Completed,"""CID3616321""",Bike,Rohini West,Anand Vihar ISBT,14.3,41.4,0,NaN,0,NaN,0,NaN,976,47.37,4.3,4.3,Uber Wallet
82485,2024-08-20,August,11:29:28,"""CNR1077779""",Completed,"""CID2252556""",Go Mini,Vasant Kunj,Indraprastha,8.8,26.1,0,NaN,0,NaN,0,NaN,889,40.35,4.3,4.7,Cash
87568,2024-11-05,November,17:32:53,"""CNR1077779""",Cancelled by Customer,"""CID6213303""",Premier Sedan,Greater Kailash,Madipur,19.0,0.0,1,Driver is not moving towards pickup location,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
26279,2024-11-27,November,20:54:07,"""CNR1079962""",Completed,"""CID1039185""",Go Sedan,Mansarovar Park,Model Town,2.9,42.5,0,NaN,0,NaN,0,NaN,331,19.73,4.3,4.2,Cash
148881,2024-12-15,December,09:21:59,"""CNR1079962""",Completed,"""CID1210517""",Auto,Nirman Vihar,Maidan Garhi,14.6,27.7,0,NaN,0,NaN,0,NaN,117,13.96,3.1,4.9,UPI
100164,2024-07-04,July,15:46:39,"""CNR1091682""",Cancelled by Customer,"""CID1131593""",Go Mini,Vishwavidyalaya,Botanical Garden,13.7,0.0,1,Change of plans,0,NaN,0,NaN,0,0.00,0.0,0.0,NaN
111121,2024-08-13,August,10:39:17,"""CNR1091682""",Completed,"""CID1590844""",eBike,Punjabi Bagh,Khan Market,7.4,43.0,0,NaN,0,NaN,0,NaN,786,5.59,4.6,4.3,Credit Card

In [18]:
# Check the values in booking outcome columns

outcome_columns = [
    "Booking Status",
    "Cancelled Rides by Customer",
    "Cancelled Rides by Driver",
    "Incomplete Rides"
]

for column in outcome_columns:
    print(f"\n--- {column} ---")

    print(df[column].value_counts(dropna=False))

--- Booking Status ---
Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

--- Cancelled Rides by Customer ---
Cancelled Rides by Customer
0    139500
1     10500
Name: count, dtype: int64

--- Cancelled Rides by Driver ---
Cancelled Rides by Driver
0    123000
1     27000
Name: count, dtype: int64

--- Incomplete Rides ---
Incomplete Rides
0    141000
1      9000
Name: count, dtype: int64

Validate numerical columns

In [19]:
# Inspect numerical columns

numeric_columns = [
    "Avg VTAT",
    "Avg CTAT",
    "Booking Value",
    "Ride Distance",
    "Driver Ratings",
    "Customer Rating"
]

display(df[numeric_columns].describe().T)

,count,mean,std,min,25%,50%,75%,max
Avg VTAT,150000.0,7.864407,4.230640,0.0,4.7,7.80,11.00,20.0
Avg CTAT,150000.0,19.821753,15.452834,0.0,0.0,22.00,32.90,45.0
Booking Value,150000.0,345.641220,403.423487,0.0,0.0,244.00,521.00,4277.0
Ride Distance,150000.0,16.753168,16.291118,0.0,0.0,13.06,30.65,50.0
Driver Ratings,150000.0,2.623215,2.082283,0.0,0.0,3.90,4.30,5.0
Customer Rating,150000.0,2.730842,2.165548,0.0,0.0,4.10,4.60,5.0

Check the Payment Method missing values

In [20]:
# Investigate Payment Method missingness by Booking Status

payment_missing_summary = (
    df.assign(
        Payment_Method_Missing=df["Payment Method"].isna()
    )
    .groupby("Booking Status")["Payment_Method_Missing"]
    .agg(
        Total_Bookings="size",
        Missing_Payment_Method="sum"
    )
)

payment_missing_summary["Missing_Percentage"] = (
    payment_missing_summary["Missing_Payment_Method"]
    / payment_missing_summary["Total_Bookings"]
    * 100
).round(2)

display(payment_missing_summary)

,Total_Bookings,Missing_Payment_Method,Missing_Percentage
Booking Status,,,
Cancelled by Customer,10500,10500,100.0
Cancelled by Driver,27000,27000,100.0
Completed,93000,0,0.0
Incomplete,9000,0,0.0
No Driver Found,10500,10500,100.0

#— Booking Outcome Consistency

## Business Objective

Verify whether the cancellation and incomplete-ride indicators agree with the Booking Status column.

## Business Questions

1. Does every customer-cancelled booking have a customer cancellation indicator of 1?
2. Does every driver-cancelled booking have a driver cancellation indicator of 1?
3. Does every incomplete booking have an incomplete-ride indicator of 1?
4. Are any indicators incorrectly set to 1 for other booking statuses?

These checks will help identify inconsistent records before data cleaning.

In [21]:
# Check booking status against cancellation indicators

checks = {
    "Customer Cancellation": (
        (df["Booking Status"] == "Cancelled by Customer")
        == (df["Cancelled Rides by Customer"] == 1)
    ),

    "Driver Cancellation": (
        (df["Booking Status"] == "Cancelled by Driver")
        == (df["Cancelled Rides by Driver"] == 1)
    ),

    "Incomplete Ride": (
        (df["Booking Status"] == "Incomplete")
        == (df["Incomplete Rides"] == 1)
    )
}

for name, result in checks.items():
    print(f"\n{name}")
    print("Matching records:", result.sum())
    print("Mismatching records:", (~result).sum())

Customer Cancellation
Matching records: 150000
Mismatching records: 0

Driver Cancellation
Matching records: 150000
Mismatching records: 0

Incomplete Ride
Matching records: 150000
Mismatching records: 0

Check numerical business rules

In [22]:
# Check potentially invalid numerical values

print("Negative Booking Values:",
      (df["Booking Value"] < 0).sum())

print("Negative Ride Distances:",
      (df["Ride Distance"] < 0).sum())

print("Negative Avg VTAT:",
      (df["Avg VTAT"] < 0).sum())

print("Negative Avg CTAT:",
      (df["Avg CTAT"] < 0).sum())

print("Driver Ratings outside 0-5:",
      (~df["Driver Ratings"].between(0, 5)).sum())

print("Customer Ratings outside 0-5:",
      (~df["Customer Rating"].between(0, 5)).sum())

Negative Booking Values: 0
Negative Ride Distances: 0
Negative Avg VTAT: 0
Negative Avg CTAT: 0
Driver Ratings outside 0-5: 0
Customer Ratings outside 0-5: 0

Investigate zero values by Booking Status

In [23]:
# Investigate zero values by booking outcome

zero_summary = (
    df.groupby("Booking Status")
    .agg(
        Total_Bookings=("Booking ID", "size"),

        Zero_Booking_Value=(
            "Booking Value",
            lambda x: (x == 0).sum()
        ),

        Zero_Ride_Distance=(
            "Ride Distance",
            lambda x: (x == 0).sum()
        ),

        Zero_Driver_Rating=(
            "Driver Ratings",
            lambda x: (x == 0).sum()
        ),

        Zero_Customer_Rating=(
            "Customer Rating",
            lambda x: (x == 0).sum()
        )
    )
)

display(zero_summary)

,Total_Bookings,Zero_Booking_Value,Zero_Ride_Distance,Zero_Driver_Rating,Zero_Customer_Rating
Booking Status,,,,,
Cancelled by Customer,10500,10500,10500,10500,10500
Cancelled by Driver,27000,27000,27000,27000,27000
Completed,93000,0,0,0,0
Incomplete,9000,0,0,9000,9000
No Driver Found,10500,10500,10500,10500,10500